baseURL = 'https://blog.nicholaschong.dev/'
languageCode = 'en-us'
title = "Nicholas Ch's blog"
theme = 'nostyleplease'

# themes/nostyleplease/config.toml
[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'manni'
    tabWidth           = 2

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  [params.theme_config]
    appearance        = "light"
    back_home_text    = "< back"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true
